using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoADB
{
    public enum ADBKeyEvent
    {
        KEYCODE_0 = 0,
        KEYCODE_0_ = 7,
        KEYCODE_1 = 8,
        KEYCODE_2 = 9,
        KEYCODE_3 = 10,
        KEYCODE_4 = 11,
        KEYCODE_5 = 12,
        KEYCODE_6 = 13,
        KEYCODE_7 = 14,
        KEYCODE_8 = 15,
        KEYCODE_9 = 0x10,
        KEYCODE_A = 0x1d,
        KEYCODE_ALT_LEFT = 0x39,
        KEYCODE_ALT_RIGHT = 0x3a,
        KEYCODE_APOSTROPHE = 0x4b,
        KEYCODE_APP_SWITCH = 0xbb,
        KEYCODE_AT = 0x4d,
        KEYCODE_B = 30,
        KEYCODE_BACK = 4,
        KEYCODE_BACKSLASH = 0x49,
        KEYCODE_C = 0x1f,
        KEYCODE_CALL = 5,
        KEYCODE_CAMERA = 0x1b,
        KEYCODE_CLEAR = 0x1c,
        KEYCODE_COMMA = 0x37,
        KEYCODE_D = 0x20,
        KEYCODE_DEL = 0x43,
        KEYCODE_DPAD_CENTER = 0x17,
        KEYCODE_DPAD_DOWN = 20,
        KEYCODE_DPAD_LEFT = 0x15,
        KEYCODE_DPAD_RIGHT = 0x16,
        KEYCODE_DPAD_UP = 0x13,
        KEYCODE_E = 0x21,
        KEYCODE_ENDCALL = 6,
        KEYCODE_ENTER = 0x42,
        KEYCODE_ENVELOPE = 0x41,
        KEYCODE_EQUALS = 70,
        KEYCODE_EXPLORER = 0x40,
        KEYCODE_F = 0x22,
        KEYCODE_FOCUS = 80,
        KEYCODE_G = 0x23,
        KEYCODE_GRAVE = 0x44,
        KEYCODE_H = 0x24,
        KEYCODE_HEADSETHOOK = 0x4f,
        KEYCODE_HOME = 3,
        KEYCODE_I = 0x25,
        KEYCODE_J = 0x26,
        KEYCODE_K = 0x27,
        KEYCODE_L = 40,
        KEYCODE_LEFT_BRACKET = 0x47,
        KEYCODE_M = 0x29,
        KEYCODE_MENU = 0x52,
        KEYCODE_MINUS = 0x45,
        KEYCODE_N = 0x2a,
        KEYCODE_NOTIFICATION = 0x53,
        KEYCODE_NUM = 0x4e,
        KEYCODE_O = 0x2b,
        KEYCODE_P = 0x2c,
        KEYCODE_PERIOD = 0x38,
        KEYCODE_PLUS = 0x51,
        KEYCODE_POUND = 0x12,
        KEYCODE_POWER = 0x1a,
        KEYCODE_Q = 0x2d,
        KEYCODE_R = 0x2e,
        KEYCODE_RIGHT_BRACKET = 0x48,
        KEYCODE_S = 0x2f,
        KEYCODE_SEMICOLON = 0x4a,
        KEYCODE_SHIFT_LEFT = 0x3b,
        KEYCODE_SHIFT_RIGHT = 60,
        KEYCODE_SLASH = 0x4c,
        KEYCODE_SOFT_LEFT = 1,
        KEYCODE_SOFT_RIGHT = 2,
        KEYCODE_SPACE = 0x3e,
        KEYCODE_STAR = 0x11,
        KEYCODE_SYM = 0x3f,
        KEYCODE_T = 0x30,
        KEYCODE_TAB = 0x3d,
        KEYCODE_U = 0x31,
        KEYCODE_V = 50,
        KEYCODE_VOLUME_DOWN = 0x19,
        KEYCODE_VOLUME_UP = 0x18,
        KEYCODE_W = 0x33,
        KEYCODE_X = 0x34,
        KEYCODE_Y = 0x35,
        KEYCODE_Z = 0x36
    }
}
